name: tests

on:
  push:
    branches:
      - "main"
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-upstream-examples
  cancel-in-progress: true

permissions:
    contents: read  # access to check out code and install dependencies

jobs:
  upstream-examples:
    name: upstream examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v6
      - name: Checkout upstream PALS repo
        uses: actions/checkout@v6
        with:
          repository: pals-project/pals
          path: pals_temp
          fetch-depth: 1
          sparse-checkout: |
            examples/
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install ".[test]"
      - name: Run upstream examples
        run: |
          for file in pals_temp/examples/*.pals.yaml; do
            python tests/validate_upstream_examples.py --path "${file}"
          done
